/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MyClass, MyObject, } from "./components/box/interfaces";
export namespace Components {
    interface XBox {
        "headerTitle": string;
        "myClassInstance": MyClass;
        "myObject": MyObject;
    }
}
declare global {
    interface HTMLXBoxElement extends Components.XBox, HTMLStencilElement {
    }
    var HTMLXBoxElement: {
        prototype: HTMLXBoxElement;
        new (): HTMLXBoxElement;
    };
    interface HTMLElementTagNameMap {
        "x-box": HTMLXBoxElement;
    }
}
declare namespace LocalJSX {
    interface XBox {
        "headerTitle"?: string;
        "myClassInstance"?: MyClass;
        "myObject"?: MyObject;
        "onEvent"?: (event: CustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "x-box": XBox;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "x-box": LocalJSX.XBox & JSXBase.HTMLAttributes<HTMLXBoxElement>;
        }
    }
}
